### ISSUE TITLE
Schema validation using SQLite/SqlCe and a specific schema fails

### ISSUE THREAD

**Issue by TiltonJH** [nhibernate/nhibernate-core#1609]
Schema validation (`NHibernateSchemaValidator.Validate()`) using SQLite (or SQL Server CE) and a specific schema fails for a generated/exported schema (`NHibernateSchemaExport.Create(false, true)`).

**Example which works:**
schema name: [n/a]
entity name: "TestEntity"

exported result:
MsSql: "dbo.TestEntity"
SQLite: "TestEntity"

No `NHibernate.SchemaValidationException`. 

**Example which fails:**
schema name: "Test"
entity name: "TestEntity"

exported result:
MsSql: "Test.TestEntity"
SQLite: "Test_TestEntity"

`NHibernate.SchemaValidationException` for SQLite (MsSql works fine):

```
Message
-------
Schema validation failed: see list of validation errors

Source
------
NHibernate

TargetSite
----------
Void ValidateSchema(NHibernate.Dialect.Dialect, NHibernate.Tool.hbm2ddl.IDatabaseMetadata)

StackTrace
----------
   bei NHibernate.Cfg.Configuration.ValidateSchema(Dialect dialect, IDatabaseMetadata databaseMetadata)
   bei NHibernate.Tool.hbm2ddl.SchemaValidator.Validate()
   ...

HResult (System.Int32)
----------------------
-2146233088

ValidationErrors (System.Collections.ObjectModel.ReadOnlyCollection`1[System.String])
-------------------------------------------------------------------------------------
0: System.String: Missing table: TestEntity
```

Somehow the specified schema gets ignored doing the validation.

Can so far be reproduced with NHibernate 4.x to 5.0.3 (never tried that with earlier versions).

**Comment by lillo42** [comment]
I'm testing with the last version of NHibernate, the problem is not happen.

this is my test:

		[Test]
		public void Validate_Schame()
		{
			var sql = new SchemaValidator(cfg);
			sql.Validate();
		}

		protected override HbmMapping GetMappings()
		{
			var mapper = new ModelMapper();
			mapper.Class<Entity>(rc =>
			{
				rc.Schema("test");
				rc.Id(x => x.Id, m => m.Generator(Generators.GuidComb));
				rc.Property(x => x.Name);
			});

			return mapper.CompileMappingForAllExplicitlyAddedEntities();
		}

**Comment by fredericDelaporte** [comment]
Thanks for the notice. Maybe #448 (v5.1) has fixed it "by the way". @TiltonJH, can you confirm it is fixed in NHibernate v5.1?

**Comment by TiltonJH** [comment]
Sounds very promising! :-)

I didn't have time yet to update to NH 5.1.x. I'm still using 5.0.3. Hopefully I will get around to it in next few days. I will keep you updated as soon as I got around to it.

(I also depend on FluentNHibernate, so I usually have to wait for them to adopt to new versions as well. But with FNH 2.1.2 depending on NH 5.1.1 I will give it a spin.)

**Comment by fredericDelaporte** [comment]
As we follow SemVer, normally a FluentNHibernate targeting NH 5.0.x should work with any NH 5.x. It should just be unable to address newer mapping features.

**Comment by TiltonJH** [comment]
Yes, I know. :-)
We\I are\am using SemVer as well.

(The thing that keeps us away is the `<runtime><assemblyBinding>*<assemblyBinding/><runtime/>` section of the *.config. (And we do have a lot of those files.)
We have strict format guideline for *.config files, which are different from what NuGet does automatically on update. So every NuGet update creates none conform files which do not actually change anything functional. Since that turned out to be very annoying, the feature gets disabled in VS. If I now actually introduce a new version which makes changes to *.config necessary. I'll be going all around the office all day telling every one again and again: "Remember the annoying change of the *.config? Yeah? Well, turn it on and update. Then turn it off again. And don't forget to format those *.config files correctly or your check in will fail ..." Or I'll have to update our entire product chain all by myself.

That's why I am always on lookout for a set of versions which do not require any adjustments to the *.configs.)

**Comment by fredericDelaporte** [comment]
Still off-topic, but that is a troublesome restriction. 5.0.3 and 5.1.1 have serious issues fixed in 5.0.6 and 5.1.3, like #1732 and #1355.

**Comment by TiltonJH** [comment]
In short: No, I can not confirm that the bug is gone. It does still exist.

Using 
```
  <package id="Antlr3.Runtime" version="3.5.1" targetFramework="net462" />
  <package id="FluentNHibernate" version="2.1.2" targetFramework="net462" />
  <package id="Iesi.Collections" version="4.0.4" targetFramework="net462" />
  <package id="log4net" version="2.0.8" targetFramework="net462" />
  <package id="NHibernate" version="5.1.3" targetFramework="net462" />
  <package id="Remotion.Linq" version="2.2.0" targetFramework="net462" />
  <package id="Remotion.Linq.EagerFetching" version="2.2.0" targetFramework="net462" />
  <package id="System.Data.SQLite.Core" version="1.0.108.0" targetFramework="net462" />
```

I use this for exporting:
```
var schemaExport = new NHibernate.Tool.hbm2ddl.SchemaExport(nhibernateConfiguration);
schemaExport.Create(false, true);
```
which creates `Test_SqliteTestEntityWithSchema`

and this for the validation:

```
var schemaValidator = new NHibernate.Tool.hbm2ddl.SchemaValidator(nhibernateConfiguration);
schemaValidator.Validate();
```

which gets me this Exception:
```
NHibernate.SchemaValidationException
====================================

Message
-------
Schema validation failed: see list of validation errors

Source
------
NHibernate

TargetSite
----------
Void ValidateSchema(NHibernate.Dialect.Dialect, NHibernate.Tool.hbm2ddl.IDatabaseMetadata)

StackTrace
----------
   bei NHibernate.Cfg.Configuration.ValidateSchema(Dialect dialect, IDatabaseMetadata databaseMetadata)
   bei NHibernate.Tool.hbm2ddl.SchemaValidator.Validate()
   ...

HResult (System.Int32)
----------------------
-2146233088

ValidationErrors (System.Collections.ObjectModel.ReadOnlyCollection`1[System.String])
-------------------------------------------------------------------------------------
0: System.String: Missing table: SqliteTestEntityWithSchema
```



My test class and mapping:

```
	/// <summary>
	/// <para xml:lang="en">A test entity for SQLite with schema.</para>
	/// <para xml:lang="de">Eine Test-Entität für SQLite mit Schema.</para>
	/// </summary>
	public class SqliteTestEntityWithSchema
	{
		private Guid? id = null;

		private int rowVersion = 0;

		/// <summary>
		/// <para xml:lang="en">Gets or sets the globally unique identifier (<see cref="Guid"/>) for this instance.</para>
		/// <para xml:lang="de">Ruft ab oder setzt den global eindeutigen Bezeichner (<see cref="Guid"/>) dieser Instanz.</para>
		/// </summary>
		public virtual Guid Id
		{
			get
			{
				if (!this.id.HasValue)
				{
					this.id = GuidGenerator.GenerateNewSequentialGuid();
				}

				return this.id.Value;
			}

			set
			{
				this.id = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets or sets the row version number for this instance.</para>
		/// <para xml:lang="de">Ruft ab oder setzt die Zeilenversionsnummer für diese Instanz.</para>
		/// </summary>
		/// <remarks>
		/// <para xml:lang="en">
		/// It is used by NHibernate to check for concurrency.
		/// Concurrency: Two or more people might be editing and saving the same object at the same time.
		/// The value will increment when the object is saved by NHibernate.
		/// </para>
		/// <para xml:lang="de">
		/// Wird von NHibernate benutzt um Gleichzeitigkeit feststellen.
		/// Gleichzeitigkeit: Zwei oder mehre Personen könnten dasselbe Objekt bearbeiten und speichern zur gleichen Zeit.
		/// Der Wert wird erhöht wenn das Objekt von NHibernate gespeichert wird.
		/// </para>
		/// </remarks>
		public virtual int RowVersion
		{
			get { return this.rowVersion; }
			protected set { this.rowVersion = value; }
		}

		/// <summary>
		/// <para xml:lang="en">Gets or sets the value for this instance.</para>
		/// <para xml:lang="de">Ruft ab oder setzt den Wert dieser Instanz.</para>
		/// </summary>
		public virtual int Value { get; set; }
	}

	/// <summary>
	/// <para xml:lang="en">The mapping class of <see cref="SqliteTestEntityWithSchema"/>.</para>
	/// <para xml:lang="de">Die Zuordnungsklasse von <see cref="SqliteTestEntityWithSchema"/>.</para>
	/// </summary>
	public sealed class SqliteTestEntityWithSchemaMap :
		ClassMap<SqliteTestEntityWithSchema>
	{
		/// <summary>
		/// <para xml:lang="en">Initializes a <see langword="new"/> instance of <see cref="SqliteTestEntityWithSchemaMap"/> and maps the properties of <see cref="TestEntity"/>.</para>
		/// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="SqliteTestEntityWithSchemaMap"/>-Klasse und ordnet die Eigenschaften von <see cref="TestEntity"/> zu.</para>
		/// </summary>
		public SqliteTestEntityWithSchemaMap()
		{
			this.DynamicInsert();
			this.DynamicUpdate();

			this.Schema("Test");

			this.Id(x => x.Id)
				.Not.Nullable()
				.GeneratedBy
				.Assigned();

			this.Version(x => x.RowVersion)
				.Not.Nullable()
				.UnsavedValue("0");

			this.Map(x => x.Value)
				.Not.Nullable();
		}
	}
```

**Comment by lillo42** [comment]
@fredericDelaporte make any sense add support to [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) , we can use this lib on .NET Core

**Comment by fredericDelaporte** [comment]
> @fredericDelaporte make any sense add support to [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) , we can use this lib on .NET Core

No, see #1638.

**Comment by jmroyb** [comment]
Hi folks,

Please can somebody confirm it is solved or not?

I think this is not still working in 5.2.6 and fails, but my scenario is a little bit different:

- Created a new driver (Based on nh build in SQLite20Driver.cs driver)
- Ciphed Microsoft.Data.Sqlite 3.0.0  (based on [https://www.bricelam.net/2016/06/13/sqlite-encryption.htm](url) )
- SQLitePCLRaw.bundle_sqlcipher 1.1.14

This is nh.xml file:

`
<hibernate-configuration xmlns="urn:nhibernate-configuration-2.2" >
	<session-factory name="prova">
		<property name="dialect">
		ProtectedSQLite.Dialect, ProtectedSQLite
		</property>
		<property name="connection.driver_class">
		ProtectedSQLite.Driver, ProtectedSQLite
		</property>
		<property name="connection.connection_string">
		Data Source=F:\prova.sqlite;
		</property>
		<property name="hbm2ddl.auto">update</property>   <- Fails
	</session-factory> 
</hibernate-configuration>
`
 I attach the project.

Cheers

[Project.zip](https://github.com/nhibernate/nhibernate-core/files/3643810/Project.zip)

**Comment by hazzik** [comment]
@jmroyb you have to implement schema metadata for your custom provider.

**Comment by jmroyb** [comment]
Please, can you provide a link?

Cheers

**Comment by fredericDelaporte** [comment]
Standard schema metadata classes are [here](https://github.com/nhibernate/nhibernate-core/tree/master/src/NHibernate/Dialect/Schema).

**Comment by TiltonJH** [comment]
Hello,

I could not update my version of NHibernate until now.

I tested it with NHibernate 5.3.5 in .NET 4.8 and I can confirm with great pleasure that the bug is fixed :)

And a big thank you to all involved.
