### ISSUE TITLE
Prevent calling UpdateTimesStampsCache for non cached entites

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2129]
When query cache enabled, I realized that we are storing updatetimestampscache for non cached entities.
Is this really necessary in our scenario we use query cache for just Cache.ReadWrite or Cache.Readonly or Cache.NonstrictReadWrite entities, not non cached entities.

We need high performance to do that we need to decrease Sync. and locking for dml/select operations, its locks all threads in same application its too much cost for per operation.

I think that this needs to be configurable(Store all entities updatetimestampscache or just cacheable entities) or we give us a way to implement our UpdateTimestampsCache, because its readonly?

> Action Queue can be check? executable.PropertySpaces && execuatble.Persister.Cache != null
```c#
                 private void RegisterCleanupActions(IExecutable executable)
		{
			if (executable is IAsyncExecutable asyncExecutable)
			{
				RegisterProcess(asyncExecutable.BeforeTransactionCompletionProcess);
				RegisterProcess(asyncExecutable.AfterTransactionCompletionProcess);
			}
			else
			{
#pragma warning disable 618,619
				RegisterProcess(executable.BeforeTransactionCompletionProcess);
				RegisterProcess(executable.AfterTransactionCompletionProcess);
#pragma warning restore 618,619
			}
			if (executable.PropertySpaces != null)
			{
				executedSpaces.UnionWith(executable.PropertySpaces);
			}
		}
```

**Comment by gokhanabatay** [comment]
Thank you quick reply @hazzik  but i think this is not Trivial issue, because when second level cache enabled there is huge performance fall down test could show this.

Summary;
ReadWriteCache has lock problems and slower than database if we did not use "in memory" second level cache.
Please take a consideration early release of (#2115  #2129) thank you.

Oracle Exa Data Database 500 Thread Api Call

2 db read(very little tables), 1 Cache read(Read-Write Cache), 1 insert

1. Second level cache disabled, query cache disabled
![test01](https://user-images.githubusercontent.com/9988911/56135488-86571600-5f99-11e9-86ea-e193e288c739.PNG)

2. Second level cache enabled with master code
![test02](https://user-images.githubusercontent.com/9988911/56135717-ffef0400-5f99-11e9-89d7-2562441640ed.PNG)

3. Second level cache enabled with your fixes including #2115  #2129
![test03](https://user-images.githubusercontent.com/9988911/56135680-eea5f780-5f99-11e9-92c6-2dadc38cd574.PNG)

------------------------------------------------------------------------------------------------------
2 db read(very little tables), 1 Cache read(Nonstrick Read-Write Cache), 1 insert

1. Second level cache enabled with master code
![test04](https://user-images.githubusercontent.com/9988911/56136484-91ab4100-5f9b-11e9-8ce4-6ab1fcfb10e4.PNG)

2. Second level cache enabled with your fixes including #2115  #2129
![test05](https://user-images.githubusercontent.com/9988911/56136923-67a64e80-5f9c-11e9-88b7-cd5ecaee3717.PNG)

**Comment by maca88** [comment]
> ReadWriteCache has lock problems and slower than database if we did not use "in memory" second level cache.

#2147 should fix that.

**Comment by gokhanabatay** [comment]
@hazzik , @maca88  hi issue still exists when do you plan to merge and make a release.

**Comment by gokhanabatay** [comment]
https://github.com/nhibernate/nhibernate-core/pull/2744 should fix this issue
