### ISSUE TITLE
How to correctly make join by IQueryable with NHibernate

### ISSUE THREAD

**Issue by RockNHawk** [nhibernate/nhibernate-core#2478]
Hi,

I have searched may document about how to correctly make join by IQueryable with NHibernate, but sill cant make it work.

I have tried join like this:

	var queryableLinq = (from user in _session3.Query<AppUserPartIndex>()
		join cii in _session3.Query<ContentItemIndex>() on user.DocumentId equals cii.DocumentId 
		where userIds.Contains(user.UserId) && cii.Published == true
		select user);
					
	var items = queryableLinq.ToList();
	Console.WriteLine(items);

but throws `Path expected for join` SemanticException.

	NHibernate.Hql.Ast.ANTLR.SemanticException: Path expected for join! [
		.......
	   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.CreateFromJoinElement(IASTNode path, IASTNode alias, Int32 joinType, IASTNode fetchNode, IASTNode propertyFetch, IASTNode with)
	   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.joinElement()
	   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromElement()
		.....
	   at NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate()
	   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(String collectionRole)
		.....

Or add an statement `into` like this:

	var queryableLinq = (from user in _session3.Query<AppUserPartIndex>()
		join cii in _session3.Query<ContentItemIndex>() on user.DocumentId equals cii.DocumentId into alias
		from a in alias
		where userIds.Contains(user.UserId) && a.Published == true
		select user);

but throws `The method or operation is not implemented` NotImplementedException

	System.NotImplementedException: The method or operation is not implemented.
	   at NHibernate.Linq.Visitors.QueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
	   at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
	   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
	   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	   at NHibernate.Linq.Visitors.QueryModelVisitor.Visit()
	   at NHibernate.Linq.Visitors.QueryModelVisitor.GenerateHqlQuery(QueryModel queryModel, VisitorParameters parameters, Boolean root, Nullable`1 rootReturnType)
	   at NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter)
		.....

Or split join statement to two IQueryable like this:

	var queryableLinq = (
		from user in _session3.Query<AppUserPartIndex>()
		from cii in _session3.Query<ContentItemIndex>()
		where user.DocumentId == cii.DocumentId && userIds.Contains(user.UserId) &&
			  cii.Published == true
		select user);

	var items = queryableLinq.ToList();
	Console.WriteLine(items);

but also throws `Path expected for join` SemanticException.

I use `NHibernate 5.3.2`, how can I do join with IQueryable ? Thanks!

[assembly: AssemblyFileVersion("5.3.2.0")]
[assembly: AssemblyInformationalVersion("5.3.2+ed36de0de7ca8bcfb512b4878cb50e7dcd5b54b9")]

see also:

https://github.com/nhibernate/nhibernate-core/issues/864

https://github.com/nhibernate/nhibernate-core/pull/2037

https://stackoverflow.com/questions/13394759/how-to-use-join-with-multiple-conditions-in-linq-to-nhibernate

https://stackoverflow.com/questions/14425749/how-linq-to-nhibernate-by-join-and-separate-where-in-query

https://groups.google.com/forum/#!searchin/nhusers/query$20join%7Csort:date

**Comment by bahusoid** [comment]
>but throws Path expected for join SemanticException.

Seems like https://github.com/nhibernate/nhibernate-core/issues/2463 which is already fixed in 5.3.2 version

**Comment by RockNHawk** [comment]
@bahusoid 

Thank you for your response, I have checked I use the latest version `NHibernate 5.3.2`, but still have this problem.

[assembly: AssemblyFileVersion("5.3.2.0")]
[assembly: AssemblyInformationalVersion("5.3.2+ed36de0de7ca8bcfb512b4878cb50e7dcd5b54b9")]

**Comment by bahusoid** [comment]
Does direct query over `ContentItemIndex` work?
```C#
var result = _session3.Query<ContentItemIndex>().FirstOrDefault();
```
Can you share mapping for `ContentItemIndex` class?

**Comment by RockNHawk** [comment]
@bahusoid it works well if no join.

	public class ContentItemIndexMap : ClassMap<ContentItemIndex>
	{
		public ContentItemIndexMap()
		{
			this.Table("zj_op_ContentItemIndex");
			Not.LazyLoad();
			this.Id(x => x.Id);
			this.Map(x => x.Author);
			this.Map(x => x.Latest);
			this.Map(x => x.Owner);
			this.Map(x => x.DisplayText);
			this.Map(x => x.CreatedUtc);
			this.Map(x => x.Published);
			this.Map(x => x.PublishedUtc);
			this.Map(x => x.ContentType);
			this.Map(x => x.ContentItemId);
			this.Map(x => x.ContentItemVersionId);
			this.Map(x => x.ModifiedUtc);
			this.Map(x => x.DocumentId);
		}
	}

**Comment by RockNHawk** [comment]
@bahusoid 

I'am very sorry I forgot add mapping  for `ContentItemIndex` , after add a mapping, join query works.
and although no mapping a simply query just return null, not mapping error throw out.

     var result = _session3.Query<ContentItemIndex>().FirstOrDefault();


Thank you very much!
